### PR TITLE
Add the test Docear4Word v1.3.1-beta.bin.zip. 

### PR DESCRIPTION
**Pull request by allen501pc**
The application cannot work because Add-in Express license is due.

### CODE REVIEW

**Comment by Joeran** [comment]
I tried the beta file that you copied to our dropbox, and it seems to work fine:

image

**Comment by Joeran** [comment]
only the version number is still 1.30 (should be 1.3.1)

image

**Comment by Joeran** [comment]
sorry, and another problem: if I try to add two or more references...
image

nothing happens, i.e. no reference is added
image

**Comment by allen501pc** [comment]
Due to the unavailable license of Add-in Express for .Net, the control items cannot be worked by using Add-in Express during execution.

**Pull request merged**
